[".config/alacritty/catppuccin-mocha.toml"]
    type = "file"
    url = "https://github.com/catppuccin/alacritty/blob/main/catppuccin-mocha.toml"
    refreshPeriod = "168h"

[".config/bat/themes/Catppuccin Mocha.tmTheme"]
    type = "file"
    url = "https://github.com/catppuccin/bat/blob/main/themes/Catppuccin%20Mocha.tmTheme"
    refreshPeriod = "168h"
    run_after_external = "bat cache --build"

[".config/btop/themes/catppuccin_mocha.theme"]
    type = "file"
    url = "https://github.com/catppuccin/btop/blob/main/themes/catppuccin_mocha.theme"
    refreshPeriod = "168h"

[".config/delta/catppuccin.gitconfig"]
    type = "file"
    url = "https://raw.githubusercontent.com/catppuccin/delta/refs/heads/main/catppuccin.gitconfig"
    refreshPeriod = "168h"
