[env]
TERM = "xterm-256color"

[font]
size = 16
[font.normal]
family = "Lilex Nerd Font Mono"
style = "Regular"

[selection]
save_to_clipboard = true

[window]
blur = true
opacity = 0.6
startup_mode = "Maximized"
decorations = "Buttonless"

[general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]
