import = ["$XDG_CONFIG_HOME/alacritty/catppuccin-mocha.toml"]

[font]
size = 16
[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"

[selection]
save_to_clipboard = true

[window]
blur = true
opacity = 0.6
startup_mode = "Maximized"
decorations = "None"
